export const themeConfig = {
  light: {
    background: 'bg-white',
    text: 'text-gray-900',
    textSecondary: 'text-gray-700',
    textMuted: 'text-gray-500',
    primary: 'text-blue-600',
    primaryHover: 'hover:text-blue-700',
    secondary: 'text-gray-600',
    accent: 'text-yellow-500',
    border: 'border-gray-200',
    buttonPrimary: 'bg-blue-500 hover:bg-blue-600 text-white',
    buttonSecondary: 'bg-gray-100 hover:bg-gray-200 text-gray-900',
    cardBg: 'bg-white',
    cardBorder: 'border-gray-200',
    gradientFrom: 'from-blue-50',
    gradientVia: 'via-white',
    gradientTo: 'to-blue-50/50',
    headerBg: 'bg-white/80',
    navText: 'text-gray-600',
    navTextHover: 'hover:text-blue-600',
    shadow: 'shadow-lg shadow-gray-200/50'
  },
  dark: {
    background: 'bg-gray-950',
    text: 'text-gray-100',
    textSecondary: 'text-gray-300',
    textMuted: 'text-gray-400',
    primary: 'text-blue-400',
    primaryHover: 'hover:text-blue-300',
    secondary: 'text-gray-400',
    accent: 'text-blue-500',
    border: 'border-gray-800',
    buttonPrimary: 'bg-blue-500 hover:bg-blue-600 text-white',
    buttonSecondary: 'bg-gray-800 hover:bg-gray-700 text-gray-100',
    cardBg: 'bg-gray-900',
    cardBorder: 'border-gray-800',
    gradientFrom: 'from-gray-950',
    gradientVia: 'via-gray-900',
    gradientTo: 'to-blue-950/30',
    headerBg: 'bg-gray-950/80',
    navText: 'text-gray-400',
    navTextHover: 'hover:text-blue-400',
    shadow: 'shadow-lg shadow-blue-500/10'
  }
} as const 