export const themeConfig = {
  light: {
    background: 'bg-gradient-to-br from-white/90 to-blue-50/90 relative before:absolute before:inset-0 before:bg-[url("/images/devops-bg.jpg")] before:bg-cover before:bg-center before:bg-fixed before:opacity-20 before:-z-10',
    text: 'text-gray-900',
    textSecondary: 'text-gray-700',
    textMuted: 'text-gray-500',
    primary: 'text-blue-600',
    primaryHover: 'hover:text-blue-700',
    secondary: 'text-gray-600',
    accent: 'text-blue-500',
    border: 'border-gray-200',
    buttonPrimary: 'bg-blue-500 hover:bg-blue-600 text-white',
    buttonSecondary: 'bg-gray-100 hover:bg-gray-200 text-gray-900',
    cardBg: 'bg-white/80 backdrop-blur-sm',
    cardBorder: 'border-gray-200/50',
    gradientFrom: 'from-blue-50/80',
    gradientVia: 'via-white/90',
    gradientTo: 'to-blue-50/70',
    headerBg: 'bg-white/70 backdrop-blur-md',
    navText: 'text-gray-600',
    navTextHover: 'hover:text-blue-600',
    shadow: 'shadow-lg shadow-blue-200/30',
    overlay: 'bg-white/40'
  },
  dark: {
    background: 'bg-gradient-to-br from-gray-950 to-blue-950 relative before:absolute before:inset-0 before:bg-[url("/images/devops-bg.jpg")] before:bg-cover before:bg-center before:bg-fixed before:opacity-30 before:blend-overlay before:-z-10',
    text: 'text-gray-100',
    textSecondary: 'text-gray-300',
    textMuted: 'text-gray-400',
    primary: 'text-blue-400',
    primaryHover: 'hover:text-blue-300',
    secondary: 'text-gray-400',
    accent: 'text-blue-500',
    border: 'border-gray-800/50',
    buttonPrimary: 'bg-blue-500 hover:bg-blue-600 text-white',
    buttonSecondary: 'bg-gray-800/80 hover:bg-gray-700 text-gray-100',
    cardBg: 'bg-gray-900/70 backdrop-blur-sm',
    cardBorder: 'border-gray-800/50',
    gradientFrom: 'from-gray-950/90',
    gradientVia: 'via-gray-900/80',
    gradientTo: 'to-blue-950/70',
    headerBg: 'bg-gray-950/70 backdrop-blur-md',
    navText: 'text-gray-400',
    navTextHover: 'hover:text-blue-400',
    shadow: 'shadow-lg shadow-blue-500/20',
    overlay: 'bg-gray-950/40'
  }
} as const 